import { blogMetadata } from "@/lib/blog-metadata";
import { BlogPostShell } from "@/components/BlogPostShell";
import { PullQuote } from "@/components/BlogVisual";
import { BlogJsonLd } from "@/components/BlogJsonLd";
import Link from "next/link";

export const metadata = blogMetadata("how-to-use-qr-codes-for-marketing", {
  title: "How to Use QR Codes for Marketing (Without Looking Cheap) | Sounez",
  description:
    "QR codes are everywhere again. Here's how to use them in print, packaging, events and social media in a way that actually converts.",
    ogTitle: "How to Use QR Codes for Marketing",
    ogDescription: "Use QR codes with a clear destination, label, and placement so people know what they are scanning.",
});

const FAQS = [
  { question: "Do QR codes expire?", answer: "Static QR codes (like those generated by the Sounez QR Code Generator) never expire — the code is just an encoded URL or text string. Dynamic QR codes from third-party paid services may stop redirecting if you cancel the subscription." },
  { question: "Can I use a QR code on a dark background?", answer: "Yes, but invert the colors carefully. The dark modules must remain darker than the light modules — you can swap black for white and white for your dark background, but you cannot use two similar shades. Test on multiple phones before printing at scale." },
  { question: "What's the best file format for printing?", answer: "SVG for vector printing — it scales to any size without pixelation and works with professional print workflows. PNG at 1000px or higher for digital use. Avoid exporting at 72dpi for print; that will look blurry at real-world sizes." },
  { question: "Should I put a QR code on my social media posts?", answer: "Generally no. People are already on a screen and can tap a link. QR codes shine in physical contexts — print, packaging, signage — where a direct tap is not possible. The exception is a presentation slide shown in-person, where audience members can scan from their seats." },
  { question: "How do I track how many people scanned my QR code?", answer: "A plain QR code gives you no scan data. The simplest solution is to wrap your destination URL in a short link with analytics (Bitly, Short.io, or a UTM-tagged URL in Google Analytics). You will see scans as clicks in your analytics dashboard." },
  { question: "What is the minimum size for a printable QR code?", answer: "The ISO 18004 standard recommends a minimum print size of 2cm × 2cm for reliable scanning at normal distances. For outdoor signage scanned from further away, scale up proportionally — a billboard-style placement would need 10cm or larger." },
];

export default function Post() {
  return (
    <>
      <BlogJsonLd
        slug="how-to-use-qr-codes-for-marketing"
        title="How to Use QR Codes for Marketing (Without Looking Cheap)"
        description="QR codes are everywhere again. Here's how to use them in print, packaging, events and social media in a way that actually converts."
        articleSection="Creator Tools"
        faqs={FAQS}
      />
      <BlogPostShell
        slug="how-to-use-qr-codes-for-marketing"
        ctaTools={["qr-code-generator", "hashtag-generator", "word-counter"]}
        title="How to Use QR Codes for Marketing (Without Looking Cheap)"
        excerpt="QR codes are everywhere again, on packaging, business cards, menus, event badges and social posts. Here's how to use them in a way that actually works and looks intentional."
      >
        <p>
          QR codes had a rough decade. They were clunky, required a separate app, and felt like a
          desperate attempt to bridge print and digital. Then the pandemic happened, every phone got a
          native scanner, and suddenly QR codes became the fastest way to move someone from the
          physical world to your digital one.
        </p>
        <p>
          Done right, a well-placed QR code is a legitimate marketing tool. A poorly placed one still
          looks cheap. Here&apos;s the difference.
        </p>

        <h2>Where QR codes actually work</h2>
        <p>
          The best QR code placements share one thing: the person scanning has a clear reason to do
          so and a working phone in their hand.
        </p>
        <ul>
          <li>
            <strong>Business cards</strong>: link to your portfolio, LinkedIn, or a contact page.
            Far more useful than a URL that&apos;s too long to type.
          </li>
          <li>
            <strong>Product packaging</strong>: link to setup guides, warranty registration, or a
            loyalty program. Reduces support tickets and builds a direct customer relationship.
          </li>
          <li>
            <strong>Event badges and lanyards</strong>: link to your speaker bio, slide deck, or
            social profile. Networking at scale.
          </li>
          <li>
            <strong>Posters and flyers</strong>: link to a ticket page, RSVP form, or playlist.
            Always include a short URL too, since not everyone will scan.
          </li>
          <li>
            <strong>Restaurant menus</strong>: the pandemic use case that stuck. Link to the full
            menu, allergen info, or an ordering system.
          </li>
          <li>
            <strong>YouTube end screens and thumbnails</strong>: link to a newsletter signup or
            Discord. Converts passive viewers into owned-audience members.
          </li>
        </ul>

        <h2>Where QR codes fail</h2>
        <ul>
          <li>
            <strong>Billboards and moving vehicles</strong>: nobody can scan a QR code at 70 mph.
          </li>
          <li>
            <strong>Digital screens</strong>: linking from one screen to another screen is almost
            always worse than a clickable link.
          </li>
          <li>
            <strong>Without context</strong>: a QR code with no label is a trust problem. Always
            tell people what they&apos;re scanning into.
          </li>
        </ul>

        <PullQuote>
          A QR code without a label is a trust problem. Always tell people where it leads.
        </PullQuote>

        <h2>The anatomy of a good QR code placement</h2>
        <p>Every effective QR code placement has four elements. Most failures come from skipping at least one of them.</p>
        <ol>
          <li>
            <strong>A clear call to action</strong>: &quot;Scan to get the free guide&quot; beats a naked QR
            code every time. The label removes the cognitive friction of deciding whether to scan.
            People are less likely to scan something that does not immediately tell them what they
            will get. Keep it to 5-7 words and make the benefit obvious — &quot;Scan for 10% off&quot; works;
            &quot;Scan here&quot; does not.
          </li>
          <li>
            <strong>A short URL fallback</strong>: not everyone will scan, and that is fine. A short,
            readable URL like &quot;sounez.com/guide&quot; gives a second path for people who prefer to type.
            It also signals that the destination is real and not hiding behind an opaque code. If
            your URL is long, use a shortener like Short.io or Bitly before encoding.
          </li>
          <li>
            <strong>Enough white space (quiet zone) around it</strong>: scanners need a clear
            margin, called a quiet zone, of at least 4 modules (the small squares that make up the
            code) on all sides. Crowding the code with text, other graphics, or a tight crop will
            cause scan failures. The ISO 18004 standard recommends a quiet zone of at least 4× the
            module size. When in doubt, leave more space than you think is necessary.
          </li>
          <li>
            <strong>A destination worth visiting</strong>: the QR code is only as good as the page
            it leads to. A slow, mobile-unfriendly landing page wastes every scan. Test the
            destination on a phone before printing anything. The page should load in under 3 seconds
            on a mobile connection, have a clear headline that matches the call to action, and not
            immediately ask for personal information before delivering on the promise.
          </li>
        </ol>

        <h2>Real campaign examples</h2>
        <p>
          Seeing how QR codes fit into real workflows makes it easier to decide whether and how to use
          them in your own work.
        </p>
        <ul>
          <li>
            <strong>Restaurant chain, menu refresh</strong>: printed table tents with &quot;Scan for today&apos;s
            specials&quot;. QR linked to a mobile-optimized specials page updated daily. Result: zero
            reprint costs when the menu changed, and the URL allowed tracking which tables scanned
            most often.
          </li>
          <li>
            <strong>Event speaker, networking</strong>: conference badge included &quot;Scan to connect on
            LinkedIn&quot; with a QR code linking to the speaker&apos;s LinkedIn profile URL. More effective
            than exchanging cards because the action was immediate and the connection persisted.
          </li>
          <li>
            <strong>Product packaging, warranty registration</strong>: a household appliance brand
            replaced the paper warranty card with a QR code linking to a simple one-page form.
            Registration rate increased because the friction of finding, completing, and mailing a
            card was removed.
          </li>
          <li>
            <strong>Creator, YouTube end card</strong>: a QR code overlay in the final 10 seconds
            linked to a newsletter signup page. Worked especially well when the video was repurposed
            as an in-person presentation, where viewers could not tap a link.
          </li>
        </ul>

        <h2>Generate your QR code in seconds</h2>
        <p>
          Use the <Link href="/tools/qr-code-generator">Sounez QR Code Generator</Link> to create codes for URLs,
          plain text, email addresses, phone numbers, and Wi-Fi credentials. It&apos;s free, runs in your
          browser, and produces clean, high-resolution codes ready for print or digital use. No
          account, no watermark.
        </p>

        <h2>Design tips: make it look intentional</h2>
        <ul>
          <li>
            Use your brand colors if your generator supports it. A colored QR code looks designed,
            not dropped in.
          </li>
          <li>
            The{" "}
            <a href="https://www.iso.org/standard/62021.html" target="_blank" rel="noopener noreferrer">
              ISO 18004 QR code standard
            </a>{" "}
            defines four error correction levels (L, M, Q, H). Keep the level at &quot;M&quot; or &quot;H&quot; for
            print, as it allows the code to scan even if slightly damaged.
          </li>
          <li>
            Test on multiple devices before printing. What scans on an iPhone may not scan on an
            older Android.
          </li>
          <li>
            Minimum print size: 2cm x 2cm. Smaller and scanners struggle.
          </li>
        </ul>

        <h2>Track your QR code performance</h2>
        <p>
          A plain QR code gives you no data. Use a URL shortener with analytics (Bitly, Short.io) as
          the destination, then wrap that in your QR code. You&apos;ll see exactly how many people scanned,
          when, and from which location, invaluable for print campaigns.
        </p>

        <h2>Frequently Asked Questions</h2>
        <h3>Do QR codes expire?</h3>
        <p>
          Static QR codes (like those from the <Link href="/tools/qr-code-generator">Sounez generator</Link>) never
          expire — the code is just an encoded URL or text string. Dynamic QR codes from third-party paid
          services may stop redirecting if you cancel the subscription.
        </p>
        <h3>Can I use a QR code on a dark background?</h3>
        <p>
          Yes, but invert the colors carefully. The dark modules must remain darker than the light
          modules. Test on multiple phones before printing at scale.
        </p>
        <h3>What&apos;s the best file format for printing?</h3>
        <p>
          SVG for vector printing (scales to any size without pixelation). PNG at 1000px or higher
          for digital use. Avoid low-resolution exports for anything that will be physically printed.
        </p>
        <h3>Should I put a QR code on my social media posts?</h3>
        <p>
          Generally no. People are already on a screen and can tap a link. QR codes work best in
          physical contexts — print, packaging, signage — where a direct tap is not possible.
        </p>
        <h3>How do I track scan performance?</h3>
        <p>
          Use a URL shortener with analytics (Bitly, Short.io) or a UTM-tagged URL as the QR destination.
          Scans register as link clicks in your analytics dashboard, giving you date, location, and device data.
        </p>
        <h3>What is the minimum size for a printable QR code?</h3>
        <p>
          The ISO 18004 standard recommends a minimum of 2cm × 2cm for reliable close-range scanning.
          Scale up for larger signage or any application scanned from more than arm&apos;s length away.
        </p>

        <h2>Conclusion: use them with intent</h2>
        <p>
          QR codes are a bridge, not a destination. Use them where a physical-to-digital jump makes
          sense, label them clearly, and make sure the destination is worth the scan. Generate yours
          now with the <Link href="/tools/qr-code-generator">QR Code Generator</Link>, free, no signup, ready in
          seconds.
        </p>
      </BlogPostShell>
    </>
  );
}
