/** Static public routes used for sitemap generation. */
export const SITE_PATHS: string[] = [
  "/",
  "/about",
  "/blog",
  "/blog/best-color-palettes-for-design",
  "/blog/best-free-tools-for-creators",
  "/blog/how-to-compress-images",
  "/blog/how-to-create-a-strong-password",
  "/blog/how-to-grow-on-tiktok",
  "/categories",
  "/categories/creator-tools",
  "/categories/design-tools",
  "/categories/utility-tools",
  "/contact",
  "/color-palette-generator",
  "/css-gradient-generator",
  "/hashtag-generator",
  "/image-compressor",
  "/password-generator",
  "/qr-code-generator",
  "/text-case-converter",
  "/tiktok-money-calculator",
  "/tools",
  "/word-counter",
  "/youtube-tags-generator",
];
