import type { Metadata } from "next";
import { SmartLink as Link } from "@/components/smart-link";
import { FileText, Mail } from "lucide-react";
import { getSiteUrl } from "@/lib/site-url";

const pageUrl = `${getSiteUrl()}/terms-of-service`;

export const metadata: Metadata = {
  title: "Terms of Service | Sounez",
  description:
    "Read the Terms of Service for Sounez. These terms explain how you may use our free online tools, what is prohibited, and how we handle intellectual property and liability.",
  alternates: { canonical: pageUrl },
  openGraph: {
    title: "Terms of Service | Sounez",
    description: "The terms that govern your use of Sounez and its free online tools.",
    url: pageUrl,
  },
};

const LAST_UPDATED = "May 26, 2026";

export default function TermsOfServicePage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6">
      <header className="mb-12 text-center">
        <div className="mx-auto mb-4 inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-brand text-primary-foreground shadow-pop">
          <FileText className="h-6 w-6" />
        </div>
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">Terms of Service</h1>
        <p className="mt-4 text-muted-foreground">
          Last updated: <time dateTime="2026-05-26">{LAST_UPDATED}</time>
        </p>
        <p className="mx-auto mt-4 max-w-xl text-base leading-relaxed text-muted-foreground">
          Please read these terms before using Sounez. By accessing or using our website and tools,
          you agree to be bound by these terms.
        </p>
      </header>

      <div className="space-y-10 rounded-3xl border border-border bg-card p-6 shadow-soft sm:p-10">

        {/* 1 */}
        <section>
          <h2 className="text-xl font-bold tracking-tight">1. Acceptance of Terms</h2>
          <div className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
            <p>
              By accessing or using Sounez (&quot;the website&quot;, &quot;the service&quot;) at{" "}
              <a href="https://www.sounez.com" className="font-medium text-primary hover:underline">
                sounez.com
              </a>
              , you agree to comply with and be bound by these Terms of Service and our{" "}
              <Link href="/privacy-policy" className="font-medium text-primary hover:underline">
                Privacy Policy
              </Link>
              .
            </p>
            <p>
              If you do not agree to these terms, please do not use the website. We reserve the
              right to update these terms at any time. Continued use of the website after changes
              are posted constitutes your acceptance of the revised terms.
            </p>
          </div>
        </section>

        <hr className="border-border" />

        {/* 2 */}
        <section>
          <h2 className="text-xl font-bold tracking-tight">2. Permitted Use</h2>
          <div className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
            <p>
              Sounez grants you a limited, non-exclusive, non-transferable, revocable licence to
              access and use the website for personal and general purposes.
            </p>
            <p>
              You may use the tools for personal, educational, and commercial projects. You may
              share links to Sounez tools. You may use outputs generated by Sounez tools (such as
              compressed images, QR codes, passwords, or color palettes) freely in your own work.
            </p>
          </div>
        </section>

        <hr className="border-border" />

        {/* 3 */}
        <section>
          <h2 className="text-xl font-bold tracking-tight">3. Prohibited Use</h2>
          <div className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
            <p>The following uses of Sounez are not permitted:</p>
            <ul className="ml-5 list-disc space-y-1.5">
              <li>Using the website for any unlawful purpose or in violation of applicable laws.</li>
              <li>
                Attempting to gain unauthorised access to any part of the website, its servers, or
                related systems.
              </li>
              <li>
                Using automated tools such as bots, scrapers, or crawlers to extract content from
                the website without prior written permission.
              </li>
              <li>
                Interfering with or disrupting the performance or integrity of the website or its
                infrastructure.
              </li>
              <li>
                Reproducing, duplicating, copying, selling, or exploiting any portion of the website
                for commercial resale purposes without our express written consent.
              </li>
              <li>
                Transmitting harmful, offensive, or disruptive content through any feature of the
                website, including the contact form or comment fields.
              </li>
              <li>
                Uploading or processing files you do not own or lack permission to use, including
                copyrighted documents, images, or media.
              </li>
              <li>
                Using AI-generated outputs (captions, notes, descriptions, resumes) dishonestly —
                for example cheating, impersonation, or submitting work you did not create.
              </li>
              <li>
                Posting spam, promotional links, or abusive material in comments.
              </li>
              <li>
                Attempting to reverse-engineer, decompile, or extract source code from any part of
                the Sounez platform.
              </li>
              <li>
                Using the website in any way that could damage the reputation of Sounez or its
                operators.
              </li>
            </ul>
          </div>
        </section>

        <hr className="border-border" />

        {/* 4 */}
        <section>
          <h2 className="text-xl font-bold tracking-tight">4. Tool Usage and Limitations</h2>
          <div className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
            <p>
              All tools on Sounez are provided free of charge. While we aim to keep them working
              reliably, the tools are provided on an &quot;as is&quot; basis without guarantees of
              availability, accuracy, or fitness for any specific purpose.
            </p>
            <p>
              You are solely responsible for how you use the output from our tools. AI-generated
              content may be inaccurate — review and edit it before publishing, submitting, or
              sharing. Always verify important results independently before relying on them.
            </p>
            <p>
              Free tools are offered with fair-use limits. Server-backed features may be rate-limited
              to keep the service available for everyone.
            </p>
            <p>
              We reserve the right to modify, suspend, or discontinue any tool at any time without
              notice.
            </p>
          </div>
        </section>

        <hr className="border-border" />

        {/* 5 */}
        <section>
          <h2 className="text-xl font-bold tracking-tight">5. Files and User-Submitted Content</h2>
          <div className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
            <p>
              Many Sounez tools process files and inputs in your browser. For those tools, content
              stays on your device unless you choose to share it elsewhere.
            </p>
            <p>
              AI, PDF, and other server-backed tools may securely process the content you submit to
              generate results. We do not retain uploads beyond what is needed to complete the
              request. See our{" "}
              <Link href="/privacy-policy" className="font-medium text-primary hover:underline">
                Privacy Policy
              </Link>{" "}
              for details.
            </p>
            <p>
              Comments you submit may be stored for moderation. We may approve, reject, or remove
              comments at our discretion. Optional email addresses in comments are not shown publicly.
            </p>
            <p>
              For copyright concerns and takedown requests, see our{" "}
              <Link href="/dmca" className="font-medium text-primary hover:underline">
                DMCA / Copyright
              </Link>{" "}
              page.
            </p>
            <p>
              You are responsible for ensuring you have the right to use any files or content you
              submit to Sounez tools. You must not submit content that:
            </p>
            <ul className="ml-5 list-disc space-y-1.5">
              <li>Infringes any third-party intellectual property rights.</li>
              <li>Contains malware, viruses, or other harmful code.</li>
              <li>Violates any applicable law or regulation.</li>
              <li>Is illegal, harmful, or offensive in nature.</li>
            </ul>
            <p>
              We make no claim of ownership over any files you upload or any outputs you generate
              using our tools.
            </p>
          </div>
        </section>

        <hr className="border-border" />

        {/* 6 */}
        <section>
          <h2 className="text-xl font-bold tracking-tight">6. Intellectual Property</h2>
          <div className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
            <p>
              All content on Sounez, including text, graphics, logos, icons, tool designs, and
              code, is the property of Sounez or its content suppliers and is protected by
              applicable intellectual property laws.
            </p>
            <p>
              You may not reproduce, distribute, modify, or create derivative works from any content
              on this website without our express written permission.
            </p>
            <p>
              Output generated by Sounez tools (such as passwords, QR codes, or colour palettes) is
              yours to use freely. We make no claim of ownership over content you create using our
              tools.
            </p>
          </div>
        </section>

        <hr className="border-border" />

        {/* 7 */}
        <section>
          <h2 className="text-xl font-bold tracking-tight">7. Disclaimer of Warranties</h2>
          <div className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
            <p>
              Sounez is provided &quot;as is&quot; and &quot;as available&quot; without any
              warranties of any kind, either express or implied, including but not limited to
              implied warranties of merchantability, fitness for a particular purpose, or
              non-infringement.
            </p>
            <p>
              We do not warrant that the website will be uninterrupted, error-free, or free of
              harmful components. We do not warrant the accuracy, completeness, or suitability of
              any information or tool output.
            </p>
          </div>
        </section>

        <hr className="border-border" />

        {/* 8 */}
        <section>
          <h2 className="text-xl font-bold tracking-tight">8. Limitation of Liability</h2>
          <div className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
            <p>
              To the fullest extent permitted by applicable law, Sounez and its operators shall not
              be liable for any indirect, incidental, special, consequential, or punitive damages
              arising from your use of, or inability to use, the website or its tools.
            </p>
            <p>
              This includes, without limitation, damages for loss of profits, data, goodwill, or
              other intangible losses, even if we have been advised of the possibility of such
              damages.
            </p>
            <p>
              Our total liability to you for any claim arising from your use of the website shall
              not exceed the amount you paid to use the service. Since the service is free, this
              amount is zero.
            </p>
          </div>
        </section>

        <hr className="border-border" />

        {/* 9 */}
        <section>
          <h2 className="text-xl font-bold tracking-tight">9. Third-Party Links</h2>
          <div className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
            <p>
              Sounez may contain links to third-party websites or services. These links are provided
              for convenience only. We have no control over the content, privacy practices, or
              availability of those sites.
            </p>
            <p>
              The inclusion of any link does not imply endorsement by Sounez. We are not responsible
              for any loss or damage that may arise from your use of third-party websites.
            </p>
          </div>
        </section>

        <hr className="border-border" />

        {/* 10 */}
        <section>
          <h2 className="text-xl font-bold tracking-tight">10. Advertising</h2>
          <div className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
            <p>
              Sounez displays advertisements served by Google AdSense and potentially other
              third-party advertising networks. These ads help us keep the service free for
              everyone.
            </p>
            <p>
              We are not responsible for the content of advertisements displayed on the website.
              Please review the advertiser&apos;s own terms and privacy policy before engaging with
              any ad.
            </p>
          </div>
        </section>

        <hr className="border-border" />

        {/* 11 */}
        <section>
          <h2 className="text-xl font-bold tracking-tight">11. Termination of Access</h2>
          <div className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
            <p>
              We reserve the right to restrict or terminate access to Sounez for any user who
              violates these terms or uses the website in a way that is harmful, abusive, or
              unlawful.
            </p>
            <p>
              Since Sounez does not require an account, access restriction may be implemented at the
              network level. We may also take other reasonable steps to prevent continued misuse.
            </p>
          </div>
        </section>

        <hr className="border-border" />

        {/* 12 */}
        <section>
          <h2 className="text-xl font-bold tracking-tight">12. Changes to These Terms</h2>
          <div className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
            <p>
              We may update these Terms of Service at any time. Changes will be effective
              immediately upon posting to this page, with an updated date at the top.
            </p>
            <p>
              It is your responsibility to review these terms periodically. Continued use of Sounez
              after changes are posted means you accept the updated terms.
            </p>
          </div>
        </section>

        <hr className="border-border" />

        {/* 13 */}
        <section>
          <h2 className="text-xl font-bold tracking-tight">13. Governing Law</h2>
          <div className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
            <p>
              These terms shall be governed by and construed in accordance with applicable laws.
              Any disputes arising from these terms or your use of the website shall be resolved
              through good-faith negotiation in the first instance.
            </p>
          </div>
        </section>

        <hr className="border-border" />

        {/* 14 */}
        <section>
          <h2 className="text-xl font-bold tracking-tight">14. Contact Us</h2>
          <div className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
            <p>If you have questions about these Terms of Service, please contact us:</p>
            <a
              href="mailto:hello@sounez.com"
              className="inline-flex items-center gap-2 font-medium text-primary hover:underline"
            >
              <Mail className="h-4 w-4" />
              hello@sounez.com
            </a>
            <p>
              Or use our{" "}
              <Link href="/contact" className="font-medium text-primary hover:underline">
                contact form
              </Link>
              .
            </p>
          </div>
        </section>
      </div>

      <div className="mt-8 flex flex-wrap justify-center gap-4 text-sm text-muted-foreground">
        <Link href="/privacy-policy" className="hover:text-foreground hover:underline">
          Privacy Policy
        </Link>
        <span aria-hidden>·</span>
        <Link href="/contact" className="hover:text-foreground hover:underline">
          Contact
        </Link>
        <span aria-hidden>·</span>
        <Link href="/" className="hover:text-foreground hover:underline">
          Home
        </Link>
      </div>
    </div>
  );
}
