/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeTagsGeneratorRouteImport } from './routes/youtube-tags-generator'
import { Route as WordCounterRouteImport } from './routes/word-counter'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TiktokMoneyCalculatorRouteImport } from './routes/tiktok-money-calculator'
import { Route as TextCaseConverterRouteImport } from './routes/text-case-converter'
import { Route as QrCodeGeneratorRouteImport } from './routes/qr-code-generator'
import { Route as PasswordGeneratorRouteImport } from './routes/password-generator'
import { Route as ImageCompressorRouteImport } from './routes/image-compressor'
import { Route as HashtagGeneratorRouteImport } from './routes/hashtag-generator'
import { Route as CssGradientGeneratorRouteImport } from './routes/css-gradient-generator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ColorPaletteGeneratorRouteImport } from './routes/color-palette-generator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as CategoriesUtilityToolsRouteImport } from './routes/categories.utility-tools'
import { Route as CategoriesDesignToolsRouteImport } from './routes/categories.design-tools'
import { Route as CategoriesCreatorToolsRouteImport } from './routes/categories.creator-tools'
import { Route as BlogHowToGrowOnTiktokRouteImport } from './routes/blog.how-to-grow-on-tiktok'
import { Route as BlogHowToCreateAStrongPasswordRouteImport } from './routes/blog.how-to-create-a-strong-password'
import { Route as BlogHowToCompressImagesRouteImport } from './routes/blog.how-to-compress-images'
import { Route as BlogBestFreeToolsForCreatorsRouteImport } from './routes/blog.best-free-tools-for-creators'
import { Route as BlogBestColorPalettesForDesignRouteImport } from './routes/blog.best-color-palettes-for-design'

const YoutubeTagsGeneratorRoute = YoutubeTagsGeneratorRouteImport.update({
  id: '/youtube-tags-generator',
  path: '/youtube-tags-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const WordCounterRoute = WordCounterRouteImport.update({
  id: '/word-counter',
  path: '/word-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokMoneyCalculatorRoute = TiktokMoneyCalculatorRouteImport.update({
  id: '/tiktok-money-calculator',
  path: '/tiktok-money-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const TextCaseConverterRoute = TextCaseConverterRouteImport.update({
  id: '/text-case-converter',
  path: '/text-case-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeGeneratorRoute = QrCodeGeneratorRouteImport.update({
  id: '/qr-code-generator',
  path: '/qr-code-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordGeneratorRoute = PasswordGeneratorRouteImport.update({
  id: '/password-generator',
  path: '/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCompressorRoute = ImageCompressorRouteImport.update({
  id: '/image-compressor',
  path: '/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const HashtagGeneratorRoute = HashtagGeneratorRouteImport.update({
  id: '/hashtag-generator',
  path: '/hashtag-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const CssGradientGeneratorRoute = CssGradientGeneratorRouteImport.update({
  id: '/css-gradient-generator',
  path: '/css-gradient-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorPaletteGeneratorRoute = ColorPaletteGeneratorRouteImport.update({
  id: '/color-palette-generator',
  path: '/color-palette-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesUtilityToolsRoute = CategoriesUtilityToolsRouteImport.update({
  id: '/categories/utility-tools',
  path: '/categories/utility-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesDesignToolsRoute = CategoriesDesignToolsRouteImport.update({
  id: '/categories/design-tools',
  path: '/categories/design-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCreatorToolsRoute = CategoriesCreatorToolsRouteImport.update({
  id: '/categories/creator-tools',
  path: '/categories/creator-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHowToGrowOnTiktokRoute = BlogHowToGrowOnTiktokRouteImport.update({
  id: '/blog/how-to-grow-on-tiktok',
  path: '/blog/how-to-grow-on-tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHowToCreateAStrongPasswordRoute =
  BlogHowToCreateAStrongPasswordRouteImport.update({
    id: '/blog/how-to-create-a-strong-password',
    path: '/blog/how-to-create-a-strong-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToCompressImagesRoute = BlogHowToCompressImagesRouteImport.update({
  id: '/blog/how-to-compress-images',
  path: '/blog/how-to-compress-images',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBestFreeToolsForCreatorsRoute =
  BlogBestFreeToolsForCreatorsRouteImport.update({
    id: '/blog/best-free-tools-for-creators',
    path: '/blog/best-free-tools-for-creators',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBestColorPalettesForDesignRoute =
  BlogBestColorPalettesForDesignRouteImport.update({
    id: '/blog/best-color-palettes-for-design',
    path: '/blog/best-color-palettes-for-design',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/color-palette-generator': typeof ColorPaletteGeneratorRoute
  '/contact': typeof ContactRoute
  '/css-gradient-generator': typeof CssGradientGeneratorRoute
  '/hashtag-generator': typeof HashtagGeneratorRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/text-case-converter': typeof TextCaseConverterRoute
  '/tiktok-money-calculator': typeof TiktokMoneyCalculatorRoute
  '/tools': typeof ToolsRoute
  '/word-counter': typeof WordCounterRoute
  '/youtube-tags-generator': typeof YoutubeTagsGeneratorRoute
  '/blog/best-color-palettes-for-design': typeof BlogBestColorPalettesForDesignRoute
  '/blog/best-free-tools-for-creators': typeof BlogBestFreeToolsForCreatorsRoute
  '/blog/how-to-compress-images': typeof BlogHowToCompressImagesRoute
  '/blog/how-to-create-a-strong-password': typeof BlogHowToCreateAStrongPasswordRoute
  '/blog/how-to-grow-on-tiktok': typeof BlogHowToGrowOnTiktokRoute
  '/categories/creator-tools': typeof CategoriesCreatorToolsRoute
  '/categories/design-tools': typeof CategoriesDesignToolsRoute
  '/categories/utility-tools': typeof CategoriesUtilityToolsRoute
  '/blog/': typeof BlogIndexRoute
  '/categories/': typeof CategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/color-palette-generator': typeof ColorPaletteGeneratorRoute
  '/contact': typeof ContactRoute
  '/css-gradient-generator': typeof CssGradientGeneratorRoute
  '/hashtag-generator': typeof HashtagGeneratorRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/text-case-converter': typeof TextCaseConverterRoute
  '/tiktok-money-calculator': typeof TiktokMoneyCalculatorRoute
  '/tools': typeof ToolsRoute
  '/word-counter': typeof WordCounterRoute
  '/youtube-tags-generator': typeof YoutubeTagsGeneratorRoute
  '/blog/best-color-palettes-for-design': typeof BlogBestColorPalettesForDesignRoute
  '/blog/best-free-tools-for-creators': typeof BlogBestFreeToolsForCreatorsRoute
  '/blog/how-to-compress-images': typeof BlogHowToCompressImagesRoute
  '/blog/how-to-create-a-strong-password': typeof BlogHowToCreateAStrongPasswordRoute
  '/blog/how-to-grow-on-tiktok': typeof BlogHowToGrowOnTiktokRoute
  '/categories/creator-tools': typeof CategoriesCreatorToolsRoute
  '/categories/design-tools': typeof CategoriesDesignToolsRoute
  '/categories/utility-tools': typeof CategoriesUtilityToolsRoute
  '/blog': typeof BlogIndexRoute
  '/categories': typeof CategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/color-palette-generator': typeof ColorPaletteGeneratorRoute
  '/contact': typeof ContactRoute
  '/css-gradient-generator': typeof CssGradientGeneratorRoute
  '/hashtag-generator': typeof HashtagGeneratorRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/text-case-converter': typeof TextCaseConverterRoute
  '/tiktok-money-calculator': typeof TiktokMoneyCalculatorRoute
  '/tools': typeof ToolsRoute
  '/word-counter': typeof WordCounterRoute
  '/youtube-tags-generator': typeof YoutubeTagsGeneratorRoute
  '/blog/best-color-palettes-for-design': typeof BlogBestColorPalettesForDesignRoute
  '/blog/best-free-tools-for-creators': typeof BlogBestFreeToolsForCreatorsRoute
  '/blog/how-to-compress-images': typeof BlogHowToCompressImagesRoute
  '/blog/how-to-create-a-strong-password': typeof BlogHowToCreateAStrongPasswordRoute
  '/blog/how-to-grow-on-tiktok': typeof BlogHowToGrowOnTiktokRoute
  '/categories/creator-tools': typeof CategoriesCreatorToolsRoute
  '/categories/design-tools': typeof CategoriesDesignToolsRoute
  '/categories/utility-tools': typeof CategoriesUtilityToolsRoute
  '/blog/': typeof BlogIndexRoute
  '/categories/': typeof CategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/color-palette-generator'
    | '/contact'
    | '/css-gradient-generator'
    | '/hashtag-generator'
    | '/image-compressor'
    | '/password-generator'
    | '/qr-code-generator'
    | '/text-case-converter'
    | '/tiktok-money-calculator'
    | '/tools'
    | '/word-counter'
    | '/youtube-tags-generator'
    | '/blog/best-color-palettes-for-design'
    | '/blog/best-free-tools-for-creators'
    | '/blog/how-to-compress-images'
    | '/blog/how-to-create-a-strong-password'
    | '/blog/how-to-grow-on-tiktok'
    | '/categories/creator-tools'
    | '/categories/design-tools'
    | '/categories/utility-tools'
    | '/blog/'
    | '/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/color-palette-generator'
    | '/contact'
    | '/css-gradient-generator'
    | '/hashtag-generator'
    | '/image-compressor'
    | '/password-generator'
    | '/qr-code-generator'
    | '/text-case-converter'
    | '/tiktok-money-calculator'
    | '/tools'
    | '/word-counter'
    | '/youtube-tags-generator'
    | '/blog/best-color-palettes-for-design'
    | '/blog/best-free-tools-for-creators'
    | '/blog/how-to-compress-images'
    | '/blog/how-to-create-a-strong-password'
    | '/blog/how-to-grow-on-tiktok'
    | '/categories/creator-tools'
    | '/categories/design-tools'
    | '/categories/utility-tools'
    | '/blog'
    | '/categories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/color-palette-generator'
    | '/contact'
    | '/css-gradient-generator'
    | '/hashtag-generator'
    | '/image-compressor'
    | '/password-generator'
    | '/qr-code-generator'
    | '/text-case-converter'
    | '/tiktok-money-calculator'
    | '/tools'
    | '/word-counter'
    | '/youtube-tags-generator'
    | '/blog/best-color-palettes-for-design'
    | '/blog/best-free-tools-for-creators'
    | '/blog/how-to-compress-images'
    | '/blog/how-to-create-a-strong-password'
    | '/blog/how-to-grow-on-tiktok'
    | '/categories/creator-tools'
    | '/categories/design-tools'
    | '/categories/utility-tools'
    | '/blog/'
    | '/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ColorPaletteGeneratorRoute: typeof ColorPaletteGeneratorRoute
  ContactRoute: typeof ContactRoute
  CssGradientGeneratorRoute: typeof CssGradientGeneratorRoute
  HashtagGeneratorRoute: typeof HashtagGeneratorRoute
  ImageCompressorRoute: typeof ImageCompressorRoute
  PasswordGeneratorRoute: typeof PasswordGeneratorRoute
  QrCodeGeneratorRoute: typeof QrCodeGeneratorRoute
  TextCaseConverterRoute: typeof TextCaseConverterRoute
  TiktokMoneyCalculatorRoute: typeof TiktokMoneyCalculatorRoute
  ToolsRoute: typeof ToolsRoute
  WordCounterRoute: typeof WordCounterRoute
  YoutubeTagsGeneratorRoute: typeof YoutubeTagsGeneratorRoute
  BlogBestColorPalettesForDesignRoute: typeof BlogBestColorPalettesForDesignRoute
  BlogBestFreeToolsForCreatorsRoute: typeof BlogBestFreeToolsForCreatorsRoute
  BlogHowToCompressImagesRoute: typeof BlogHowToCompressImagesRoute
  BlogHowToCreateAStrongPasswordRoute: typeof BlogHowToCreateAStrongPasswordRoute
  BlogHowToGrowOnTiktokRoute: typeof BlogHowToGrowOnTiktokRoute
  CategoriesCreatorToolsRoute: typeof CategoriesCreatorToolsRoute
  CategoriesDesignToolsRoute: typeof CategoriesDesignToolsRoute
  CategoriesUtilityToolsRoute: typeof CategoriesUtilityToolsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube-tags-generator': {
      id: '/youtube-tags-generator'
      path: '/youtube-tags-generator'
      fullPath: '/youtube-tags-generator'
      preLoaderRoute: typeof YoutubeTagsGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word-counter': {
      id: '/word-counter'
      path: '/word-counter'
      fullPath: '/word-counter'
      preLoaderRoute: typeof WordCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok-money-calculator': {
      id: '/tiktok-money-calculator'
      path: '/tiktok-money-calculator'
      fullPath: '/tiktok-money-calculator'
      preLoaderRoute: typeof TiktokMoneyCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-case-converter': {
      id: '/text-case-converter'
      path: '/text-case-converter'
      fullPath: '/text-case-converter'
      preLoaderRoute: typeof TextCaseConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code-generator': {
      id: '/qr-code-generator'
      path: '/qr-code-generator'
      fullPath: '/qr-code-generator'
      preLoaderRoute: typeof QrCodeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-generator': {
      id: '/password-generator'
      path: '/password-generator'
      fullPath: '/password-generator'
      preLoaderRoute: typeof PasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-compressor': {
      id: '/image-compressor'
      path: '/image-compressor'
      fullPath: '/image-compressor'
      preLoaderRoute: typeof ImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hashtag-generator': {
      id: '/hashtag-generator'
      path: '/hashtag-generator'
      fullPath: '/hashtag-generator'
      preLoaderRoute: typeof HashtagGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-gradient-generator': {
      id: '/css-gradient-generator'
      path: '/css-gradient-generator'
      fullPath: '/css-gradient-generator'
      preLoaderRoute: typeof CssGradientGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-palette-generator': {
      id: '/color-palette-generator'
      path: '/color-palette-generator'
      fullPath: '/color-palette-generator'
      preLoaderRoute: typeof ColorPaletteGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/utility-tools': {
      id: '/categories/utility-tools'
      path: '/categories/utility-tools'
      fullPath: '/categories/utility-tools'
      preLoaderRoute: typeof CategoriesUtilityToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/design-tools': {
      id: '/categories/design-tools'
      path: '/categories/design-tools'
      fullPath: '/categories/design-tools'
      preLoaderRoute: typeof CategoriesDesignToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/creator-tools': {
      id: '/categories/creator-tools'
      path: '/categories/creator-tools'
      fullPath: '/categories/creator-tools'
      preLoaderRoute: typeof CategoriesCreatorToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-grow-on-tiktok': {
      id: '/blog/how-to-grow-on-tiktok'
      path: '/blog/how-to-grow-on-tiktok'
      fullPath: '/blog/how-to-grow-on-tiktok'
      preLoaderRoute: typeof BlogHowToGrowOnTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-create-a-strong-password': {
      id: '/blog/how-to-create-a-strong-password'
      path: '/blog/how-to-create-a-strong-password'
      fullPath: '/blog/how-to-create-a-strong-password'
      preLoaderRoute: typeof BlogHowToCreateAStrongPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-compress-images': {
      id: '/blog/how-to-compress-images'
      path: '/blog/how-to-compress-images'
      fullPath: '/blog/how-to-compress-images'
      preLoaderRoute: typeof BlogHowToCompressImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/best-free-tools-for-creators': {
      id: '/blog/best-free-tools-for-creators'
      path: '/blog/best-free-tools-for-creators'
      fullPath: '/blog/best-free-tools-for-creators'
      preLoaderRoute: typeof BlogBestFreeToolsForCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/best-color-palettes-for-design': {
      id: '/blog/best-color-palettes-for-design'
      path: '/blog/best-color-palettes-for-design'
      fullPath: '/blog/best-color-palettes-for-design'
      preLoaderRoute: typeof BlogBestColorPalettesForDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ColorPaletteGeneratorRoute: ColorPaletteGeneratorRoute,
  ContactRoute: ContactRoute,
  CssGradientGeneratorRoute: CssGradientGeneratorRoute,
  HashtagGeneratorRoute: HashtagGeneratorRoute,
  ImageCompressorRoute: ImageCompressorRoute,
  PasswordGeneratorRoute: PasswordGeneratorRoute,
  QrCodeGeneratorRoute: QrCodeGeneratorRoute,
  TextCaseConverterRoute: TextCaseConverterRoute,
  TiktokMoneyCalculatorRoute: TiktokMoneyCalculatorRoute,
  ToolsRoute: ToolsRoute,
  WordCounterRoute: WordCounterRoute,
  YoutubeTagsGeneratorRoute: YoutubeTagsGeneratorRoute,
  BlogBestColorPalettesForDesignRoute: BlogBestColorPalettesForDesignRoute,
  BlogBestFreeToolsForCreatorsRoute: BlogBestFreeToolsForCreatorsRoute,
  BlogHowToCompressImagesRoute: BlogHowToCompressImagesRoute,
  BlogHowToCreateAStrongPasswordRoute: BlogHowToCreateAStrongPasswordRoute,
  BlogHowToGrowOnTiktokRoute: BlogHowToGrowOnTiktokRoute,
  CategoriesCreatorToolsRoute: CategoriesCreatorToolsRoute,
  CategoriesDesignToolsRoute: CategoriesDesignToolsRoute,
  CategoriesUtilityToolsRoute: CategoriesUtilityToolsRoute,
  BlogIndexRoute: BlogIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
